config/routes.rb
  Rails.application.routes.draw do

  root to: 'pages#index', as: 'home'

  get 'about' => 'pages#about', as:'about'

  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :students
    has_many :instructors
    belongs_to :cohorts
end
 

app/models/instructor.rb
class Instructor < ApplicationRecord
    belongs_to :course
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :course
end

app/controllers/Pages_controller.rb
class PagesController < ApplicationController
def about 
    @title = 'About our class';
    @content = 'This is about page';
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def about 
    @title = 'About our class';
    @content = 'This is about page';
    end 

    def create
    
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
      @post = Post.all
    end
    
    def show 
        @post = Post.find(params[:id])
    end

    def new 
      
    end

    def create
      #render plain: params[:post].inspect
      @post = Post.new(post_params)

      @post.save
      redirect_to @post
    end

    private def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/students_controler.rb
class StudentController < ApplicationController 
    def index
        @student=Student.ApplicationController

    end
    def edit

    end 
    def update

    end 
    def destroy

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NYCDA 2.0</title>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/
        bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', '
        data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application','
        data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
    data-toggle="collapse" data-target="#navbar"
    aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"> <strong>Welcome To</strong></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=""#>NYCDA 2.0</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        <li><%= link_to "Home", home_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create Username", new_page_path %></li>
      <ul>
      </div><!--/nav-collapse-->
      </div>
      </nav>

    <div class="container">
      <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p> <%= @content %></p>

app/views/pages/create.erb
<h1>Quote of the day...</h1>

<p>"EVER TRIED.
EVER FAILED.
NO MATTER.
TRY AGAIN
FAIL AGAIN.
FAIL BETTER"!!! </p>

app/views/pages/new.html.erb
<h1>Add Students</h1>
<%= form_for :pages, url: pages_path do|f| %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>

    <p> 
        <%= f.label :password %><br>
        <%= f.text_area(:password,{:class => 'form-control'}) %>
    </p>

    <p>
        <%=f.submit({:class => 'btn btn-primary'}) %>
        </p>
    <% end %>